const events = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILED: "AUTH_FAILED",
  CHECK_TICKET: "CHECK_TICKET",
  SYNC_SCORE: "SYNC_SCORE",
  SYNC_FINISH: "SYNC_FINISH",
};

export default events;
